### PR TITLE
Add basic build and CI

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This is similar to what we have for the open-telemetry/opentelemetry-collector-releases repository: 

https://github.com/open-telemetry/opentelemetry-collector-releases

**Comment by jpkrohling** [comment]
@fstab, @gouthamve, would one of you like to review this one?

**Comment by gouthamve** [comment]
LGTM tbh, but its a lot more bash magic than I'd like.

**Comment by jpkrohling** [comment]
> its a lot more bash magic than I'd like

True, just wait to see the next PR 🙂  I did consider other alternatives like Ruby, but I think people might know bash better than Ruby. I'm open to suggestions, though.

**Pull request merged**
