### PR TITLE
fix auto-update script to handle new go modules from core

### PR DESCRIPTION
**Pull request by rlankfo**
Signed-off-by: Robbie Lankford <robert.lankford@grafana.com>

@jpkrohling I saw your comment on #37 and updated the script. Feel free to close if this isn't what you had in mind.

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
This looks about right! Thanks!

**Comment by jpkrohling** [comment]
I've seen a failure when running the workflow manually, but it's likely unrelated to this PR:

```
jq: error: Could not open file latest-core.json: No such file or directory
date: invalid date ‘+%s’
jq: error: Could not open file latest-contrib.json: No such file or directory
date: invalid date ‘+%s’
./scripts/update-to-latest-otelcol.sh: line 48: ((: <  : syntax error: operand expected (error token is "<  ")
```

**Comment by rlankfo** [comment]
Are you on a mac? Running it locally on mac I had to make sure to use GNU date or I had the same error.

**Comment by jpkrohling** [comment]
Linux, but this error came from the CI.

**Comment by rlankfo** [comment]
Ahh this does look like a different error than I saw locally but now I'm curious, I'll look into it a bit later today.

**Pull request merged**
