### PR TITLE
gcomapiprocessor: CanonicalHeaderKey for X-Scope-OrgID

### PR DESCRIPTION
**Pull request by rlankfo**

### CODE REVIEW

**Review by kovrus — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]
I think there should be a test for this change, to ensure it fixes the issue, but I won't block this from being merged

**Comment by rlankfo** [comment]
> I think there should be a test for this change, to ensure it fixes the issue, but I won't block this from being merged

Thanks @jpkrohling. Adding a test _should_ be straight forward I think, I'll look into it today.

**Comment by rlankfo** [comment]
@jpkrohling I added a test case for this and it passes. I don't know that this proves it will fix the issue because the existing test cases (w/o canonical header key) don't fail like we see at runtime.

**Comment by leveyjam** [comment]
```
// Extract X-Scope-OrgID
key := http.CanonicalHeaderKey(orgID)
```
https://pkg.go.dev/net/http#CanonicalHeaderKey

```
The canonicalization converts the first letter and any letter following a hyphen to upper case; the rest are converted to lowercase.
```

So that will convert X-Scope-OrgID to X-Scope-Orgid based on my reading @jpkrohling @rlankfo 
We see 500s in Dev for every request - can this be changed / rolled-back?

**Comment by rlankfo** [comment]
> ```
> 
> // Extract X-Scope-OrgID
> 
> key := http.CanonicalHeaderKey(orgID)
> 
> ```
> 
> https://pkg.go.dev/net/http#CanonicalHeaderKey
> 
> 
> 
> ```
> 
> The canonicalization converts the first letter and any letter following a hyphen to upper case; the rest are converted to lowercase.
> 
> ```
> 
> 
> 
> So that will convert X-Scope-OrgID to X-Scope-Orgid based on my reading @jpkrohling @rlankfo 
> 
> We see 500s in Dev for every request - can this be changed / rolled-back?

This can be reverted but to be clear it didn't introduce the 500s in dev. These have been ongoing for a while since the faro collector is configured to send data to the otel collector (otlp-gateway-v2) instead of the otlp-gateway.

**Pull request merged**
